apiVersion: v1
kind: ReplicationController
metadata:
  name: lyric-backend
  labels:
    name: lyric-backend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: lyric-backend
    spec:
      containers:
      - name: lyric-backend
        # Replace  with your project ID or use `make template`
        image: asia.gcr.io/lyric-211406/lyric-backend

        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
